# Generated by Django 4.0.2 on 2022-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0007_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacant',
            field=models.CharField(default='', max_length=100),
        ),
    ]
