# Generated by Django 4.0.2 on 2022-05-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0008_job_vacant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=models.TextField(),
        ),
    ]
