# Generated by Django 4.0.2 on 2022-05-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0012_alter_job_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='coverletter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='eligibility',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='former_job',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='fullname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
